courses:
  - Medical Student
  - Nurse Student
  - Physio
  - Occupational Therapist
  - SALT

years:
  - One
  - Two
  - Three
  - Four
  - Five

types:
  - Clinic
  - Tutorial
  - Lecture
  - Ward Based Teaching
  - Theatre List
  - Other

tags:
  - Paediatrics
  - Cardiovascular
  - Surgery
  - Haematology
  - Respiratory
  - Orthopaedics
  - Renal Medicine
  - Urology
  - Acute
  - Anaesthetics
  - Rheumatology
  - Geriatrics
  - Neurology
  - Oncology
  - Radiology
